### PR TITLE
Fix various defects with Alarm function:

### PR DESCRIPTION
**Pull request by grepis**
- alarm 2 is not set due to wrong register
- alarm hour/minute/second values is not read properly during refresh
- alarm mode not read properly during refresh

### CODE REVIEW

**Review by Naguissa — APPROVED** [review]
I see the problems, but still I think there's any bit movement that doesn't attach to datasheets, I'll review it now... (I'm checking Alarm2 modes, that should correspond to constants)

**Comment by Naguissa** [comment]
I've also revamped alarm defines to addapt them to more logical order:
(being x 0 for Alarm 0, 1 for Alarm 1)
 - bit 0 - AxM1 (always 0 on Alarm 2)
 - bit 1 - AxM2
 - bit 2 - AxM3
 - bit 3 - AxM4
 - bit 4 - Ax DT/DY
 - bit 5 - Ax Enabled: 1 = enabled, 0 = disabled
 - bit 6 - Unused, always 0
 - bit 7 - Alarm 1 = 0 / Alarm 2 = 1

This way we use a common bit description for both alarms.


I've commited the changes but I have very few time these days, could you test it for me?  I've tested compilation and basics, but I have no time to test each alarm mode....


Thanks!

**Comment by grepis** [comment]
Ok, my setup is ready, so I will check tonight or tomorrow.

**Comment by grepis** [comment]
Hi once again,

Did you made any changes to alarmSet?

**Comment by Naguissa** [comment]
You're right, I missed it. I've revamped it a little, simplifying for DS1307 and rearranging bit4 and DT/DY in order to fit new _defines_

I've commited new version to master.

**Pull request merged**
