### PR TITLE
Fixed sscanf_P problem

### PR DESCRIPTION
**Pull request by ArminJo**

### CODE REVIEW

**Comment by Naguissa** [comment]
Thanks. I have implemented it in local and was about to upload it now; only changing versions and so on. I reject this to prevent conflicts.

**Comment by ArminJo** [comment]
OK thanks!

**Comment by Naguissa** [comment]
Travis processed this PR and result was correct. Now compiling my changes...

**Comment by Naguissa** [comment]
Released! In few hours should be available on IDE's Library Manager...

**Comment by ArminJo** [comment]
Great!

**Pull request closed without merging**
